---

- name: Configure name-servers
  vyos.vyos.vyos_config:
    src: nameservers.j2

#- name: Debug hostvars for r1
#  debug:
#    var: hostvars['r1']

#- name: Debug hostvars for r4
#  debug:
#    var: hostvars['r4']

- name: Configure host-name
  vyos.vyos.vyos_config:
    lines:
      - set system host-name {{ inventory_hostname }}

- name: Configure time format
  vyos.vyos.vyos_config:
    lines:
      - set system option time-format '24-hour'
  when: hostvars[inventory_hostname].vyos_version == 'rolling'
