router_id: "{{ r2_eth1_ip }}"

interfaces:
  - name: eth0
    address: "{{ r2_eth0_ip }}"
    prefix: 24
    description: WAN
    type: ethernet

  - name: eth1
    address: "{{ r2_eth1_ip }}"
    prefix: 24
    description: LAN
    type: ethernet

  - name: dum0
    address: "{{ r2_dum0_ip }}"
    prefix: 32
    description: conf-by-ansible
    type: dummy

ospf:
  networks:
    - 192.0.2.0/24
    - "{{ r2_dum0_ip }}/32"

isis:
  net: 49.0001.1920.0200.0014.00
  interfaces:
    - eth1

bgp:
  neighbor: "{{ r1_eth1_ip }}"

vpn_ipsec:
  peer: RIGHT
  connection_type: initiate
  local_id: "{{ r2_eth1_ip }}"
  remote_id: "{{ r1_eth1_ip }}"
  interface: eth1
  peer_ip: "{{ r1_eth1_ip }}"
  psk: "1234567890"
  tunnels:
    - name: 1
      local_subnet: 100.64.11.0/24
      remote_subnet: 100.64.1.0/24
    - name: 2
      local_subnet: 100.64.22.0/24
      remote_subnet: 100.64.2.0/24
