- name: Check HAProxy
  vyos.vyos.vyos_command:
    commands:
      - show haproxy
  register: ha_status_output
  tags:
    - haproxy
    - haproxy_show
    - show

- name: Fail if HAProxy has errors
  fail:
    msg: "HAProxy has errors on {{ inventory_hostname }}: {{ ha_status_output.stdout }}"
  when: ha_status_output.stdout | join('\n') is search('error|fail|down|inactive|Traceback')
  ignore_errors: yes
  tags:
    - haproxy
    - haproxy_show
    - show

- name: Display HAProxy outputs
  debug:
    var: ha_status_output.stdout_lines
  tags:
    - haproxy
    - haproxy_show
    - show
